[pytest]
testpaths = .
#python_files = test_projects_functional.py test_conversations_functional.py test_dataconnectors_functional.py
python_files = test_*
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --strict-markers -p no:randomly --html=NCP_Exposed_API_Report.html --self-contained-html
markers =
    functional: End-to-end flow tests
    members: Project members flow tests
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)-8s | %(name)s | %(message)s
